### PR TITLE
Return ID in parser function

### PR DESCRIPTION
**Pull request by malberts**
For #23 

* Use repo to get the ID
* Removed parser tests
  * I need to be able to save a page and get a real page ID. I couldn't find an easy way to do that and spending more time on that is not worth it.
* Added PHPUnit tests instead

Parser function returns:
Screenshot_20241113_153814

Same as page information:
Screenshot_20241113_154002

### CODE REVIEW

**Comment by malberts** [comment]
This made me wonder if we really need a parser function, or if a magic word would be enough. But maybe there's a future case for getting the persistent ID of a different page, in which case the parser can be reused.

More importantly, I think the original parser tests I added are useless. I need to be able to save a page and get a real page ID. I couldn't find an easy way to do that. It seems like this is better tested in PHPUnit where we can just call the parser after creating the page.

**Comment by malberts** [comment]
I ran into one issue here: the parser function value is not saved if the page is created with `{{#ppid:}}` inside. If the page content is purged, or changed later, then the value shows up.

I suspect this is always going to be a problem because it needs to save the page (and therefore its content) first before getting the ID. I'm not sure if there is another hook that can be used, or if we should trigger a purge if the page contains the parser function on creation.

**Comment by JeroenDeDauw** [comment]
> if we should trigger a purge if the page contains the parser function on creation.

I can't think of a better solution

**Comment by JeroenDeDauw** [comment]
Follow ups:
* https://github.com/ProfessionalWiki/PersistentPageIdentifiers/issues/30
* https://github.com/ProfessionalWiki/PersistentPageIdentifiers/issues/31

**Pull request merged**
